import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.steameracademy.me",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 1,
    },
    {
      url: "https://www.steameracademy.me/about",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.steameracademy.me/blogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://www.steameracademy.me/contact",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: "https://www.steameracademy.me/services",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/english-club",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/code-club",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/gallery",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/privacy-policy",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Dive%20into%20Engineering%3A%20A%20Fun%20Guide%20for%20Engineering%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/How%20to%20become%20a%20successful%20Software%20Engineer%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/How%20to%20become%20a%20successful%20Software%20Engineer%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/How%20to%20become%20a%20successful%20Software%20Engineer%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/How%20to%20become%20a%20successful%20Software%20Engineer%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/How%20to%20become%20a%20successful%20Software%20Engineer%20%F0%9F%9A%80%20!",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Understanding%20Pressure%3A%20A%20Comprehensive%20and%20Engaging%20Guide%20%F0%9F%8C%9F",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/What%20is%20a%20noun%3F%20A%20Cornerstone%20of%20Language",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/What%20is%20a%20verb%3F%20A%20Cornerstone%20of%20Language",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Verbs%3A%20The%20Backbone%20of%20Language",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Why%20X%20Always%20Gets%20the%20Spotlight%F0%9F%A4%94",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Welcome%20to%20a%20amazing%20world%20of%20mathematics",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/God%20told%20me%20to%20do%20some%20good%20things%20but%20I%20did%20many%20sin%20theta!%F0%9F%A4%93",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Part%201%3ASCIENCE%20%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80%E2%99%A1%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Part%202%3ASCIENCE%20%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80%E2%99%A1%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Part%203%3ASCIENCE%20%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80%E2%99%A1%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Part%204%3ASCIENCE%20%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80%E2%99%A1%EF%AE%A9%D9%A8%D9%80%EF%AE%A9%EF%AE%A9%D9%A8%D9%80",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Unlocking%20the%20Mysteries%20of%20the%20Universe%3A%20A%20Casual%20Dive%20into%20Physics",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/What%20is%20Physics%3F",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Computers%20and%20Programming",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: "https://www.steameracademy.me/blogs/Basic%20components%20of%20a%20computer%20and%20how%20computers%20work",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.1,
    },
  ];
}
