name: 🔨 Pull Request CI
on:
  pull_request_target:
    branches: main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true
          lfs: false
      - name: 📦 Deploy to Vercel
        uses: amondnet/vercel-action@v42
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
      - name: 🔗 Get Preview Url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
