name: 💻 Type Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7

      - name: 🍔 Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 🔨 Install dependencies
        run: bun install

      - name: 🛠 Run TypeScript Type Checking
        run: bun tsc --noEmit
